---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1d97r369nenvs7pfffykcapfjh5t5pe6jx0rvqgxh4vl57na3rs0spau2k2"
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1d97r369nenvs7pfffykcapfjh5t5pe6jx0rvqgxh4vl57na3rs0spau2k2"
