apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:IDzKjMW0QDF3FdG1mR3ggtHs1TkdL9CrLgg04GLWAb3j6mwl,iv:0A4bYVU2fWEVnRN26rBXmDj84jyCxGffBIHkjUT9zmo=,tag:B5QOuFoTwe0P7OnvpEb+pA==,type:str]
    credentials.json: ENC[AES256_GCM,data:MhKF9kL9KKAvPEmeqbRSul9vvJhqUJnzzE2fcyVy/8U9ut+Rk30YpIwlUat9auMhcFoKhxJIig+r7sh/MP9+6i/JbDyoyE2LxCixtyZM2ZZAa/JgKrmdWBC0zwDLZ6MHgaVGS0Z7asKtQBRfaSVX84Ad+ZRAt4yHPNQuj5wt61eo9EuyAxHGT1Smia/mdKEz/BjDqgu3eLOzfpkBlhy6wxp2C7Oqcl8I/I7eIt3GgA==,iv:ho3DB3IhE85fK9+4QzbRtQadOpwHIG2OnD/47Pq9fqs=,tag:Ec5W7ZU2nQnWbz0FXHci9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d97r369nenvs7pfffykcapfjh5t5pe6jx0rvqgxh4vl57na3rs0spau2k2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4LzdaUis5Zy9aQVlPN2xL
            WGlUU2FlU3dVQlpZeGJOS1hVQ21NcGpLQWtzCjdyV25wUHU1ejIxeFh6ZmpzSUsw
            d2hwbnBDQUJZb2VkaHRsdHVPaVBmZG8KLS0tIE9sZ1NkRzF4WDMwdU9WMjVGWkJl
            dGlleVI0c3FzK2VpZUFocitDZ3A4bjgKScWoq624RgsitLX5uGK1t4aEZui3sqNB
            T5ClD1/VFpMtO1GE4btLVZJjNF7MMvbXsV6u5d1mV5jN/OFMC/gT8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-11T19:36:18Z"
    mac: ENC[AES256_GCM,data:Mn3IVJFSEHLhGytcwkLk1Pr6c6PcyYuIfxQPIvqKGf8NO23c1cABgmdpmRRWjXlPEL7TcT0NZYb0MkmZ8ytaEkoSbOZOuJCn2cuJJtYAHATdNKdE/htwJlIcpsq1r27BjiJ+BxyZCf90JFbrFqCDIDTfqZHQFzvamiNM3UB8v4Y=,iv:X0rPX95oAfqc09e+DmypuN0L4/AxvYklTU8RrmCgDpA=,tag:GaTHBeSekC6p0Sy9Gp0u0w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
