apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:2lP0gUhJ47cRTq63UjvlaCrnwj6/XbTikUM2PLkqMvYMWDkbXBXbdw==,iv:EthR70KDi+f3rPqBAY4mZq+W3dZ0B8jQk7YpI6TeEdI=,tag:aKiTZAQGI2Uuh5zZt0nmbw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d97r369nenvs7pfffykcapfjh5t5pe6jx0rvqgxh4vl57na3rs0spau2k2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsbjdUUFh5V0tiNlpBUktk
            MThZcW00dEg4RnZEQjVCZG1RZDJqb3FGaWhBCjZPOHlpMVB2V1pkNkVsV3l0RUw0
            TDd0RUpyTCtMS0ZnR0JjWlVHMGdqaHMKLS0tIEIvQnNaMHQ4RTlnbXlYUE0vVTNu
            cWkwd3MrR1dLSWp1YUdCblEzNmIxRGsKyV5rSvo3Lrxww0Tu2WvNoMBqn9USh/j4
            ziKeCuA3z6727YSr4zpxBdPBNw61mFHZmEiXyNNBHgg9v5xHnL6A7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-12T16:06:40Z"
    mac: ENC[AES256_GCM,data:gD7JgsPI5MJqxI4j5pAqs6mu2Onj4fCvvFlLQOJoiYQ38S11BCTd1yIP81kSXNtjVmmRSBT58mwH9mKPqa1h7oCRDe1adYRlp04BkpB61cUWu/mR/4mI8ccGXfnR3GT5YeLxr9t1NqmEViBNZwC01zxBqPwRIpHlMoPlCabGwXw=,iv:IhJ2hYNIfek6FKsG6o1BvgU5blSwtrFlYO0vCYdlRWw=,tag:ZwhcFvg2LeTdmtl4dBLd+w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
