apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:PRjJNwtwVjLabViUtqxnP5xKtGMg5R3PXMoE/NPwAJ3GDaKf69DYVQ==,iv:KJ+GIyr/O2zg2RJwhB9wHvBuLRfH6IXcF2Ru8TlEaXM=,tag:btJ7OP7xWjAY3KGa+TbwKQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d97r369nenvs7pfffykcapfjh5t5pe6jx0rvqgxh4vl57na3rs0spau2k2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpMVlqakt4M0JXZWhMOVh6
            d2xKdjFBUGlaTEtmLy9qbUpWMVl5U0JxN0NFCkc2Rld5cjNtRkZ1aUtLTzVablNS
            WloraDhnYnZCdzkzTm95UzFqSktpN2sKLS0tIER0eFBQRnI0SXVkSVdJWEM4anRE
            cHFaR2ZVZjZXNXdKM2F0c1phNTRINWsKSYhbX7wFLD/uhEBnf+P0vgje3HaJCj59
            TJH2SNjmmNBsGgydFGNoj5UGgUNBU9z+Zf/GJ9cXj71jhA7guc7osg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-12T14:52:02Z"
    mac: ENC[AES256_GCM,data:qGQIvxApCKrKzT9iv8stLxwhiC/3GbA1My335fh9RZAwSmWEqHASWw3bdch+KFl0F77vLGIqqykfz+Sfzbl3CSLms64TJgYqWmsxICl7S7kLEAcPC/G2Yf9Y0+MDCJOqSkXMFCx7qL53NdHxA2Aco1FG6R7uS/M7cmvpJ5RFwCI=,iv:yfxurUUNKqdgoTwA2+ORN6ERt0uiVPRuO2TuChWxZLw=,tag:gdaFDdTWCwp4gMhnKx1zQQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
