apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:wfE99nks+CyAoO1p0qwssemnibnQ7aG/zTuieNZGKO9IEu0Vs2Mowg==,iv:/AIWlZ+6RBfFYGqdmnEJRV/UeYySW607JHU0q5i/058=,tag:Her2cizf6OsZxrbPrXthMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d97r369nenvs7pfffykcapfjh5t5pe6jx0rvqgxh4vl57na3rs0spau2k2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MHQ5OW8zcEFwdjdMSnIw
            RGdVUDVnaXc2eVJHblBQbHNQZFk2d1RUZmtFCm1CdE5qbnpPaERuU1ZBcjNqRE9q
            RlB2bFY2VUIyc01QbER0SFFZamVPVmsKLS0tIFNCdnhPcDZ1bk5IbkpLVVhlSDhu
            Y1RveWFWQmZEQW5hQXg1ZmJUQXhTV0kKZY3parooeYWwH2RqhOVfkTn2TDiP+hqp
            ofsIjPGxiUkSyxVa9Anst6coRMG9pidJ+YPCzNh5+WocjkFo2pxuAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-12T18:40:19Z"
    mac: ENC[AES256_GCM,data:tXnpXjHLhWZY1sWuDnKInAwpA7CcpN88lblfhgZPMu9kSdIBHdbauwCtfnbK4uVW6HlcNEtgsKBckyQGwbmOg8tp415rYyyhLSTdqEZnnraCXmxHWhVp5mY//6kWkM9HYMOafsyB8RjAErQk0fkqCWpVUjpU2ZseqbPfoatsrEQ=,iv:524KPyZLqGnmdF8cXbEIApzScOcRpRo0L+SwcQSYcQM=,tag:x7ouf8IiDqW4Pkb4yxRhWw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
